/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SetPasswordRequest {
    /** The the user's new password. */
    password?: string;
}
