/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Tesseral from "../../../../../api/index";
import * as core from "../../../../../core";
import { ApiKey } from "../../../../types/ApiKey";

export const CreateApiKeyRequest: core.serialization.Schema<
    serializers.CreateApiKeyRequest.Raw,
    Tesseral.CreateApiKeyRequest
> = core.serialization.object({
    apiKey: ApiKey.optional(),
});

export declare namespace CreateApiKeyRequest {
    export interface Raw {
        apiKey?: ApiKey.Raw | null;
    }
}
