/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class TesseralTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, TesseralTimeoutError.prototype);
    }
}
