/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateApiKeyRequest {
    updateApiKeyRequestId?: string;
    apiKey?: Tesseral.ApiKey;
}
