/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Tesseral from "../../../api/index";
import * as core from "../../../core";

export const LogoutRequest: core.serialization.Schema<serializers.LogoutRequest.Raw, Tesseral.LogoutRequest> =
    core.serialization.object({});

export declare namespace LogoutRequest {
    interface Raw {}
}
