/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Tesseral from "../../../api/index";
import * as core from "../../../core";

export const RefreshRequest: core.serialization.Schema<serializers.RefreshRequest.Raw, Tesseral.RefreshRequest> =
    core.serialization.object({
        refreshToken: core.serialization.string().optional(),
    });

export declare namespace RefreshRequest {
    interface Raw {
        refreshToken?: string | null;
    }
}
