/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information in an Access Token about the current Session.
 */
export interface AccessTokenSession {
    /** The Session ID. */
    id: string;
}
