/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information in an Access Token about the Organization the User is logged
 *  into.
 */
export interface AccessTokenOrganization {
    /** The Organization's ID. */
    id?: string;
    /** The Organization's display name. */
    displayName?: string;
}
