/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

/**
 * The claims encoded in an Access Token.
 */
export interface AccessTokenClaims {
    /**
     * Will always be of the form "https://project-xxx.tesseral.app", where
     *  "project-xxx" is your project ID.
     */
    iss?: string;
    /** Will always be equal to the `user.id` claim. */
    sub?: string;
    /** Will always be equal to the `iss` claim. */
    aud?: string;
    /** When this access token expires, in seconds since the unix epoch. */
    exp?: number;
    /** When this access token was issued, in seconds since the unix epoch. */
    nbf?: number;
    /** Will always be equal to the `nbf` claim. */
    iat?: number;
    /** The Organization the User is logged into. */
    organization?: Tesseral.AccessTokenOrganization;
    /** The User that's logged in. */
    user?: Tesseral.AccessTokenUser;
    /** The user's current Session. */
    session?: Tesseral.AccessTokenSession;
    /**
     * If this is an impersonated Session, this contains information about who on
     *  your staff is impersonating the user.
     */
    impersonator?: Tesseral.AccessTokenImpersonator;
}
