/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information in an Access Token about the logged-in User.
 */
export interface AccessTokenUser {
    /** The User's ID. */
    id?: string;
    /** The User's email. */
    email?: string;
    /** The User's display name. */
    displayName?: string;
}
