/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information in an Access Token about who is impersonating the User.
 */
export interface AccessTokenImpersonator {
    /** The email address of the individual on your staff impersonating the User. */
    email?: string;
}
