/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Additional details about an API error.
 */
export interface ApiErrorDetail {
    /** A more human-friendly error message. Exists to help make an error easier to understand. This value may change at any time. */
    description?: string;
    /** A link to documentation about this error. */
    docsLink?: string;
}
