/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKey {
    /** The API Key ID. Starts with `api_key_...`. */
    id?: string;
    /** The Organization this API Key belongs to. */
    organizationId?: string;
    /** When the API Key was created. */
    createTime?: Date;
    /** When the API Key was last updated. */
    updateTime?: Date;
    /** The expire time of the API Key. */
    expireTime?: Date;
    /** A human-readable display name for this API Key. */
    displayName?: string;
    /** The secret token for this API Key. */
    secretToken?: string;
    /** The secret token suffix for this API Key. */
    secretTokenSuffix?: string;
    /** Whether this API Key is revoked. */
    revoked?: boolean;
}
