/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKeyRoleAssignment {
    /** The API Key Role Assignment ID. Starts with `api_key_role_assignment_...`. */
    id?: string;
    /** The API Key ID. */
    apiKeyId?: string;
    /** The Role */
    roleId?: string;
}
