/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetPasskeyOptionsResponse {
    rpId?: string;
    rpName?: string;
    userId?: string;
    userDisplayName?: string;
}
