/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface ListUserInvitesResponse {
    userInvites?: Tesseral.UserInvite[];
    nextPageToken?: string;
}
