/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Organization {
    id?: string;
    displayName?: string;
    createTime?: Date;
    updateTime?: Date;
    logInWithGoogle?: boolean;
    logInWithMicrosoft?: boolean;
    logInWithEmail?: boolean;
    logInWithPassword?: boolean;
    logInWithSaml?: boolean;
    logInWithAuthenticatorApp?: boolean;
    logInWithPasskey?: boolean;
    requireMfa?: boolean;
    googleHostedDomains?: string[];
    microsoftTenantIds?: string[];
    samlEnabled?: boolean;
}
