/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Passkey {
    id?: string;
    userId?: string;
    createTime?: Date;
    updateTime?: Date;
    disabled?: boolean;
    credentialId?: string;
    publicKeyPkix?: string;
    aaguid?: string;
    rpId?: string;
}
