/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Role represents a logical grouping of permissions that Users may have.
 */
export interface Role {
    /** The Role ID. Starts with `role_...`. */
    id?: string;
    /** The Organization this Role belongs to, if any. */
    organizationId?: string;
    /** When the Role was created. */
    createTime?: Date;
    /** When the Role was last updated. */
    updateTime?: Date;
    /** A human-readable display name for this Role. */
    displayName?: string;
    /** A human-readable description of the Role. */
    description?: string;
    /** The names of the Actions associated with this Role. */
    actions?: string[];
}
