/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SamlConnection {
    id?: string;
    createTime?: Date;
    updateTime?: Date;
    primary?: boolean;
    spAcsUrl?: string;
    spEntityId?: string;
    idpRedirectUrl?: string;
    idpX509Certificate?: string;
    idpEntityId?: string;
}
