/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * UserRoleAssignment represents a User being assigned to a Role.
 */
export interface UserRoleAssignment {
    /** The User Role Assignment ID. Starts with `user_role_assignment_...`. */
    id?: string;
    /** The User ID. */
    userId?: string;
    /** The Role ID. */
    roleId?: string;
}
