/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface User {
    id?: string;
    email?: string;
    createTime?: Date;
    updateTime?: Date;
    owner?: boolean;
    googleUserId?: string;
    microsoftUserId?: string;
    hasAuthenticatorApp?: boolean;
    displayName?: string;
    profilePictureUrl?: string;
}
