/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../../../../index";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface OrganizationsUpdateOrganizationGoogleHostedDomainsRequest {
    organizationId?: string;
    body: Tesseral.OrganizationGoogleHostedDomains;
}
