/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Tesseral from "../../../../../api/index";
import * as core from "../../../../../core";
import { ApiKeyRoleAssignment } from "../../../../types/ApiKeyRoleAssignment";

export const CreateApiKeyRoleAssignmentRequest: core.serialization.Schema<
    serializers.CreateApiKeyRoleAssignmentRequest.Raw,
    Tesseral.CreateApiKeyRoleAssignmentRequest
> = core.serialization.object({
    apiKeyRoleAssignment: ApiKeyRoleAssignment.optional(),
});

export declare namespace CreateApiKeyRoleAssignmentRequest {
    export interface Raw {
        apiKeyRoleAssignment?: ApiKeyRoleAssignment.Raw | null;
    }
}
