/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Tesseral from "../../../../../api/index";
import * as core from "../../../../../core";

export const RegisterAuthenticatorAppRequest: core.serialization.Schema<
    serializers.RegisterAuthenticatorAppRequest.Raw,
    Tesseral.RegisterAuthenticatorAppRequest
> = core.serialization.object({
    totpCode: core.serialization.string().optional(),
});

export declare namespace RegisterAuthenticatorAppRequest {
    interface Raw {
        totpCode?: string | null;
    }
}
