/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Tesseral from "../../../../../api/index";
import * as core from "../../../../../core";

export const SetPasswordRequest: core.serialization.Schema<
    serializers.SetPasswordRequest.Raw,
    Tesseral.SetPasswordRequest
> = core.serialization.object({
    password: core.serialization.string().optional(),
});

export declare namespace SetPasswordRequest {
    interface Raw {
        password?: string | null;
    }
}
