/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const AccessTokenOrganization: core.serialization.ObjectSchema<
    serializers.AccessTokenOrganization.Raw,
    Tesseral.AccessTokenOrganization
> = core.serialization.object({
    id: core.serialization.string(),
    displayName: core.serialization.string(),
});

export declare namespace AccessTokenOrganization {
    export interface Raw {
        id: string;
        displayName: string;
    }
}
