/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const AccessTokenImpersonator: core.serialization.ObjectSchema<
    serializers.AccessTokenImpersonator.Raw,
    Tesseral.AccessTokenImpersonator
> = core.serialization.object({
    email: core.serialization.string().optional(),
});

export declare namespace AccessTokenImpersonator {
    interface Raw {
        email?: string | null;
    }
}
