/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const AccessTokenUser: core.serialization.ObjectSchema<
    serializers.AccessTokenUser.Raw,
    Tesseral.AccessTokenUser
> = core.serialization.object({
    id: core.serialization.string(),
    email: core.serialization.string(),
    displayName: core.serialization.string().optional(),
    profilePictureUrl: core.serialization.string().optional(),
});

export declare namespace AccessTokenUser {
    export interface Raw {
        id: string;
        email: string;
        displayName?: string | null;
        profilePictureUrl?: string | null;
    }
}
