/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const AccessTokenUser: core.serialization.ObjectSchema<
    serializers.AccessTokenUser.Raw,
    Tesseral.AccessTokenUser
> = core.serialization.object({
    id: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    displayName: core.serialization.string().optional(),
});

export declare namespace AccessTokenUser {
    interface Raw {
        id?: string | null;
        email?: string | null;
        displayName?: string | null;
    }
}
