/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const ApiErrorDetail: core.serialization.ObjectSchema<serializers.ApiErrorDetail.Raw, Tesseral.ApiErrorDetail> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        docsLink: core.serialization.string().optional(),
    });

export declare namespace ApiErrorDetail {
    interface Raw {
        description?: string | null;
        docsLink?: string | null;
    }
}
