/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const ApiKey: core.serialization.ObjectSchema<serializers.ApiKey.Raw, Tesseral.ApiKey> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        organizationId: core.serialization.string().optional(),
        createTime: core.serialization.date().optional(),
        updateTime: core.serialization.date().optional(),
        expireTime: core.serialization.date().optional(),
        displayName: core.serialization.string().optional(),
        secretToken: core.serialization.string().optional(),
        secretTokenSuffix: core.serialization.string().optional(),
        revoked: core.serialization.boolean().optional(),
    });

export declare namespace ApiKey {
    export interface Raw {
        id?: string | null;
        organizationId?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        expireTime?: string | null;
        displayName?: string | null;
        secretToken?: string | null;
        secretTokenSuffix?: string | null;
        revoked?: boolean | null;
    }
}
