/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const ApiKeyRoleAssignment: core.serialization.ObjectSchema<
    serializers.ApiKeyRoleAssignment.Raw,
    Tesseral.ApiKeyRoleAssignment
> = core.serialization.object({
    id: core.serialization.string().optional(),
    apiKeyId: core.serialization.string().optional(),
    roleId: core.serialization.string().optional(),
});

export declare namespace ApiKeyRoleAssignment {
    export interface Raw {
        id?: string | null;
        apiKeyId?: string | null;
        roleId?: string | null;
    }
}
