/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { UserInvite } from "./UserInvite";

export const CreateUserInviteResponse: core.serialization.ObjectSchema<
    serializers.CreateUserInviteResponse.Raw,
    Tesseral.CreateUserInviteResponse
> = core.serialization.object({
    userInvite: UserInvite.optional(),
});

export declare namespace CreateUserInviteResponse {
    interface Raw {
        userInvite?: UserInvite.Raw | null;
    }
}
