/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { ApiKeyRoleAssignment } from "./ApiKeyRoleAssignment";

export const CreateApiKeyRoleAssignmentResponse: core.serialization.ObjectSchema<
    serializers.CreateApiKeyRoleAssignmentResponse.Raw,
    Tesseral.CreateApiKeyRoleAssignmentResponse
> = core.serialization.object({
    apiKeyRoleAssignment: ApiKeyRoleAssignment.optional(),
});

export declare namespace CreateApiKeyRoleAssignmentResponse {
    export interface Raw {
        apiKeyRoleAssignment?: ApiKeyRoleAssignment.Raw | null;
    }
}
