/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteUserInviteResponse: core.serialization.ObjectSchema<
    serializers.DeleteUserInviteResponse.Raw,
    Tesseral.DeleteUserInviteResponse
> = core.serialization.object({});

export declare namespace DeleteUserInviteResponse {
    export interface Raw {}
}
