/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteUserResponse: core.serialization.ObjectSchema<
    serializers.DeleteUserResponse.Raw,
    Tesseral.DeleteUserResponse
> = core.serialization.object({});

export declare namespace DeleteUserResponse {
    interface Raw {}
}
