/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteApiKeyRoleAssignmentResponse: core.serialization.ObjectSchema<
    serializers.DeleteApiKeyRoleAssignmentResponse.Raw,
    Tesseral.DeleteApiKeyRoleAssignmentResponse
> = core.serialization.object({});

export declare namespace DeleteApiKeyRoleAssignmentResponse {
    export interface Raw {}
}
