/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteScimapiKeyResponse: core.serialization.ObjectSchema<
    serializers.DeleteScimapiKeyResponse.Raw,
    Tesseral.DeleteScimapiKeyResponse
> = core.serialization.object({});

export declare namespace DeleteScimapiKeyResponse {
    interface Raw {}
}
