/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteRoleResponse: core.serialization.ObjectSchema<
    serializers.DeleteRoleResponse.Raw,
    Tesseral.DeleteRoleResponse
> = core.serialization.object({});

export declare namespace DeleteRoleResponse {
    export interface Raw {}
}
