/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteMyPasskeyResponse: core.serialization.ObjectSchema<
    serializers.DeleteMyPasskeyResponse.Raw,
    Tesseral.DeleteMyPasskeyResponse
> = core.serialization.object({});

export declare namespace DeleteMyPasskeyResponse {
    export interface Raw {}
}
