/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteApiKeyResponse: core.serialization.ObjectSchema<
    serializers.DeleteApiKeyResponse.Raw,
    Tesseral.DeleteApiKeyResponse
> = core.serialization.object({});

export declare namespace DeleteApiKeyResponse {
    export interface Raw {}
}
