/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteSamlConnectionResponse: core.serialization.ObjectSchema<
    serializers.DeleteSamlConnectionResponse.Raw,
    Tesseral.DeleteSamlConnectionResponse
> = core.serialization.object({});

export declare namespace DeleteSamlConnectionResponse {
    export interface Raw {}
}
