/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const ErrorDetail: core.serialization.ObjectSchema<serializers.ErrorDetail.Raw, Tesseral.ErrorDetail> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        docsLink: core.serialization.string().optional(),
    });

export declare namespace ErrorDetail {
    export interface Raw {
        description?: string | null;
        docsLink?: string | null;
    }
}
