/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { UserInvite } from "./UserInvite";

export const GetUserInviteResponse: core.serialization.ObjectSchema<
    serializers.GetUserInviteResponse.Raw,
    Tesseral.GetUserInviteResponse
> = core.serialization.object({
    userInvite: UserInvite.optional(),
});

export declare namespace GetUserInviteResponse {
    export interface Raw {
        userInvite?: UserInvite.Raw | null;
    }
}
