/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { UserRoleAssignment } from "./UserRoleAssignment";

export const GetUserRoleAssignmentResponse: core.serialization.ObjectSchema<
    serializers.GetUserRoleAssignmentResponse.Raw,
    Tesseral.GetUserRoleAssignmentResponse
> = core.serialization.object({
    userRoleAssignment: UserRoleAssignment.optional(),
});

export declare namespace GetUserRoleAssignmentResponse {
    export interface Raw {
        userRoleAssignment?: UserRoleAssignment.Raw | null;
    }
}
