/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { UserRoleAssignment } from "./UserRoleAssignment";

export const ListUserRoleAssignmentsResponse: core.serialization.ObjectSchema<
    serializers.ListUserRoleAssignmentsResponse.Raw,
    Tesseral.ListUserRoleAssignmentsResponse
> = core.serialization.object({
    userRoleAssignments: core.serialization.list(UserRoleAssignment).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListUserRoleAssignmentsResponse {
    export interface Raw {
        userRoleAssignments?: UserRoleAssignment.Raw[] | null;
        nextPageToken?: string | null;
    }
}
