/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { ScimapiKey } from "./ScimapiKey";

export const ListScimapiKeysResponse: core.serialization.ObjectSchema<
    serializers.ListScimapiKeysResponse.Raw,
    Tesseral.ListScimapiKeysResponse
> = core.serialization.object({
    scimApiKeys: core.serialization.list(ScimapiKey).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListScimapiKeysResponse {
    export interface Raw {
        scimApiKeys?: ScimapiKey.Raw[] | null;
        nextPageToken?: string | null;
    }
}
