/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { SamlConnection } from "./SamlConnection";

export const ListSamlConnectionsResponse: core.serialization.ObjectSchema<
    serializers.ListSamlConnectionsResponse.Raw,
    Tesseral.ListSamlConnectionsResponse
> = core.serialization.object({
    samlConnections: core.serialization.list(SamlConnection).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListSamlConnectionsResponse {
    export interface Raw {
        samlConnections?: SamlConnection.Raw[] | null;
        nextPageToken?: string | null;
    }
}
