/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { UserInvite } from "./UserInvite";

export const ListUserInvitesResponse: core.serialization.ObjectSchema<
    serializers.ListUserInvitesResponse.Raw,
    Tesseral.ListUserInvitesResponse
> = core.serialization.object({
    userInvites: core.serialization.list(UserInvite).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListUserInvitesResponse {
    export interface Raw {
        userInvites?: UserInvite.Raw[] | null;
        nextPageToken?: string | null;
    }
}
