/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const LogoutResponse: core.serialization.ObjectSchema<serializers.LogoutResponse.Raw, Tesseral.LogoutResponse> =
    core.serialization.object({});

export declare namespace LogoutResponse {
    interface Raw {}
}
