/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const Passkey: core.serialization.ObjectSchema<serializers.Passkey.Raw, Tesseral.Passkey> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        userId: core.serialization.string().optional(),
        createTime: core.serialization.date().optional(),
        updateTime: core.serialization.date().optional(),
        disabled: core.serialization.boolean().optional(),
        credentialId: core.serialization.string().optional(),
        publicKeyPkix: core.serialization.string().optional(),
        aaguid: core.serialization.string().optional(),
        rpId: core.serialization.string().optional(),
    });

export declare namespace Passkey {
    interface Raw {
        id?: string | null;
        userId?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        disabled?: boolean | null;
        credentialId?: string | null;
        publicKeyPkix?: string | null;
        aaguid?: string | null;
        rpId?: string | null;
    }
}
