/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const RefreshResponse: core.serialization.ObjectSchema<
    serializers.RefreshResponse.Raw,
    Tesseral.RefreshResponse
> = core.serialization.object({
    accessToken: core.serialization.string().optional(),
});

export declare namespace RefreshResponse {
    interface Raw {
        accessToken?: string | null;
    }
}
