/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { Passkey } from "./Passkey";

export const RegisterPasskeyResponse: core.serialization.ObjectSchema<
    serializers.RegisterPasskeyResponse.Raw,
    Tesseral.RegisterPasskeyResponse
> = core.serialization.object({
    passkey: Passkey.optional(),
});

export declare namespace RegisterPasskeyResponse {
    export interface Raw {
        passkey?: Passkey.Raw | null;
    }
}
