/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const RevokeApiKeyResponse: core.serialization.ObjectSchema<
    serializers.RevokeApiKeyResponse.Raw,
    Tesseral.RevokeApiKeyResponse
> = core.serialization.object({});

export declare namespace RevokeApiKeyResponse {
    export interface Raw {}
}
