/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const Role: core.serialization.ObjectSchema<serializers.Role.Raw, Tesseral.Role> = core.serialization.object({
    id: core.serialization.string().optional(),
    organizationId: core.serialization.string().optional(),
    createTime: core.serialization.date().optional(),
    updateTime: core.serialization.date().optional(),
    displayName: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    actions: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace Role {
    export interface Raw {
        id?: string | null;
        organizationId?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        displayName?: string | null;
        description?: string | null;
        actions?: string[] | null;
    }
}
