/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const ScimapiKey: core.serialization.ObjectSchema<serializers.ScimapiKey.Raw, Tesseral.ScimapiKey> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        displayName: core.serialization.string().optional(),
        createTime: core.serialization.date().optional(),
        updateTime: core.serialization.date().optional(),
        secretToken: core.serialization.string().optional(),
        revoked: core.serialization.boolean().optional(),
    });

export declare namespace ScimapiKey {
    interface Raw {
        id?: string | null;
        displayName?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        secretToken?: string | null;
        revoked?: boolean | null;
    }
}
