/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const SetPasswordResponse: core.serialization.ObjectSchema<
    serializers.SetPasswordResponse.Raw,
    Tesseral.SetPasswordResponse
> = core.serialization.object({});

export declare namespace SetPasswordResponse {
    export interface Raw {}
}
