/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const SwitchableOrganization: core.serialization.ObjectSchema<
    serializers.SwitchableOrganization.Raw,
    Tesseral.SwitchableOrganization
> = core.serialization.object({
    id: core.serialization.string().optional(),
    displayName: core.serialization.string().optional(),
});

export declare namespace SwitchableOrganization {
    export interface Raw {
        id?: string | null;
        displayName?: string | null;
    }
}
