/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { Role } from "./Role";

export const UpdateRoleResponse: core.serialization.ObjectSchema<
    serializers.UpdateRoleResponse.Raw,
    Tesseral.UpdateRoleResponse
> = core.serialization.object({
    role: Role.optional(),
});

export declare namespace UpdateRoleResponse {
    export interface Raw {
        role?: Role.Raw | null;
    }
}
