/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const UserRoleAssignment: core.serialization.ObjectSchema<
    serializers.UserRoleAssignment.Raw,
    Tesseral.UserRoleAssignment
> = core.serialization.object({
    id: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    roleId: core.serialization.string().optional(),
});

export declare namespace UserRoleAssignment {
    export interface Raw {
        id?: string | null;
        userId?: string | null;
        roleId?: string | null;
    }
}
