/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, Tesseral.User> = core.serialization.object({
    id: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    createTime: core.serialization.date().optional(),
    updateTime: core.serialization.date().optional(),
    owner: core.serialization.boolean().optional(),
    googleUserId: core.serialization.string().optional(),
    microsoftUserId: core.serialization.string().optional(),
    hasAuthenticatorApp: core.serialization.boolean().optional(),
});

export declare namespace User {
    interface Raw {
        id?: string | null;
        email?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        owner?: boolean | null;
        googleUserId?: string | null;
        microsoftUserId?: string | null;
        hasAuthenticatorApp?: boolean | null;
    }
}
