/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { User } from "./User";

export const WhoamiResponse: core.serialization.ObjectSchema<serializers.WhoamiResponse.Raw, Tesseral.WhoamiResponse> =
    core.serialization.object({
        user: User.optional(),
    });

export declare namespace WhoamiResponse {
    interface Raw {
        user?: User.Raw | null;
    }
}
