/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UsersListUsersRequest {
    organizationId?: string;
    pageToken?: string;
}
